name: "웹프로그래밍 실습 CI/CD"

on:
    push:
        branches: 
            - main
        tags:
            - release.*

jobs:
    Job-Gue-Deul:
        runs-on: ububtu-latest
        steps: 
            - run: echo "어쩌고 저쩌고.... ${{ github.repository }}"